AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for lambda

Resources:
  GetRecipes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes
            Method: get

  GetRecipesById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-by-id.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: get

  GetRecipesByNutrients:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-by-nutrients.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/nutrients
            Method: get

  GetRecipesByIngredients:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-by-ingredients.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/ingredients
            Method: get

  GetSimilarRecipesById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-similar-by-id.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/similar/{id}
            Method: get

  GetRandomRecipes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-random.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/random
            Method: get

  GetAutocompleteSearch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-autocomplete-search.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/search
            Method: get

  GetRecipeNutrition:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-recipe-nutrition.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/{id}/nutrition
            Method: get

  SearchIngredients:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/ingredients/search.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /ingredients
            Method: get

  GetIngredientsById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/ingredients/get-ingredient-by-id.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /ingredients/{id}
            Method: get

  ComputeIngredientNutrientAmount:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/ingredients/compute-ingredient-nutrient-amount.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /ingredients/compute/{id}
            Method: get