AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for lambda

Resources:
  GetRecipes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes
            Method: get

  GetRecipesById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-by-id.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: get

  GetRecipesByNutrients:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-by-nutrients.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/nutrients
            Method: get

  GetRecipesByIngredients:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: built/src/presentation/handlers/recipes/get-by-ingredients.handle
      Runtime: nodejs18.x
      Timeout: 30
      Events:
        CreateBooks:
          Type: Api
          Properties:
            Path: /recipes/ingredients
            Method: get